---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: depression
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: depression
            port:
              number: 80

---
apiVersion: v1
kind: Service
metadata:
  name: depression
spec:
  ports:
    - port: 80
      protocol: TCP
  selector:
    app:  depression

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: depression-nginx
spec:
  selector:
    matchLabels:
      app: depression
  replicas: 3
  template:
    metadata:
      labels:
        app: depression
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: depression-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: depression-volume
        configMap:
          name: depression
